dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
      - zsh
      - gnupg
      - cryptsetup
      - pinentry-curses
      - gawk
      - libgcrypt20-dev
      - steghide
      - qrencode
      - e2fsprogs
      - python2.7

before_script:
  - make --directory=extras/kdf-keys
  - sudo make --directory=extras/kdf-keys install
  - sudo ./extras/install_cloakify.sh

script:
  - make --directory=extras/kdf-keys test
  - make test
