sudo: required
language: c

services:
  - docker

before_script:
  - docker build -t dyne/tomb .
  - docker run -it --privileged dyne/tomb /bin/bash -c "oracle & make test"

script:
  - docker run -it --privileged dyne/tomb /bin/bash -c "make --directory=extras/kdf-keys test"